[tool.poetry]
name = "ai-smart-comtract-vulnerability-detection"
version = "0.1.0"
description = ""
authors = ["gweidart"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.2"
numpy = "^1.24.0"
keras = "^3.5.0"
isort = "^5.13.2"
black = "24.2.0"
tensorflow-cpu = "^2.17.0"
eth-ape = {extras = ["recommended-plugins"], version = "^0.8.15"}
joblib = "^1.4.2"
imblearn = "^0.0"
rich = "^13.9.1"
beautifulsoup4 = "^4.12.3"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
